config/routes.rb
Rails.application.routes.draw do
  resources :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates :name, :presence => true
  validates :content, :presence => true
  validates :number, :presence => true

  def next
    if (self == Lesson.last)
      Lesson.first
    else
      next_lesson = Lesson.where("number > (?)", self.number).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.number = Lesson.all.length
    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to lessons_path
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to lessons_path
  end

  private
  def lesson_params
    params.require(:lesson).permit(:name, :content, :number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnHow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for @lesson do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render "form" %>

app/views/lessons/index.html.erb
<h1>Lessons</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= link_to lesson.name, lesson_path(lesson) %></li>
  <% end %>
</ul>

<%= link_to "New Lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= form_for @lesson do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit %>
<% end %>

app/views/lessons/show.html.erb
<h1><%= @lesson.name %></h1>
<p><%= @lesson.content %></p>

<p><%= link_to "Edit", edit_lesson_path(@lesson) %></p>
<p><%= link_to "Delete", lesson_path(@lesson), :data => {:confirm => "You sure?", :method => "delete"} %></p>

<p><%= link_to "Next Lesson", lesson_path(@lesson.next) %></p>
<p><%= link_to "Return to lessons", lessons_path %></p>